const address = ['1111 Hack Reactor Rd', '1222 Hack Reactor Rd', '2342 Hack Reactor Rd', '3413 Hack Reactor Rd'];
const city = ['San Francisco', 'San Diego', 'Los Angeles', 'San Mateo', 'New York', 'Toronto'];
const state = ['California', 'New York', 'Alabama', 'Kentucky', 'Georgia'];
const postalCode = ['42342','23423','23143','67562','67687','89813','12346'];
const tel = ['453-234-2351','252-234-6574','988-3231-3425','873-2123-6832','321-534-1234'];
const url = ['www.google.com','www.amazon.com','hackreactor.com','www.facebook.com','www.asdf.com'];
const categories = {
    Food: [
      'Afghan',
      'African',
      'South African',
      'American',
      'Arabian',
      'Argentine',
      'Armenian',
      'Asian Fusion',
      'Australian',
      'Austrian',
      'Bangladeshi',
      'Barbeque',
      'Basque',
      'Belgian',
      'Brasseries',
      'Brazilian',
      'British',
      'Buffets',
      'Burgers',
      'Burmese',
      'Cafes',
      'Themed Cafes',
      'Cafeteria',
      'Cajun Creole',
      'Caribbean',
      'Dominican',
      'Haitian',
      'Puerto Rican',
      'Trinidadian',
      'Catalan',
      'Cheesesteaks',
      'Chicken Wings',
      'Chinese',
      'Cantonese',
      'Szechuan',
      'Comfort Food',
      'Creperies',
      'Cuban',
      'Czech',
      'Delis',
      'Diners',
      'Fondue',
      'French',
      'Mauritius',
      'Reunion',
      'Game Meat',
      'Gastropubs',
      'German',
      'GlutenFree',
      'Greek',
      'Guamanian',
      'Halal',
      'Hawaiian',
      'Himalayan',
      'Hot Pot',
      'Hungarian',
      'Indian',
      'Indonesian',
      'Irish',
      'Italian',
      'Sardinian',
      'Sicilian',
      'Japanese',
      'Izakaya',
      'Japanese Curry',
      'Ramen',
      'Teppanyaki',
      'Kebab',
      'Korean',
      'Malaysian',
      'Mediterranean',
      'Falafel',
      'Mexican',
      'Tacos',
      'MiddleEastern',
      'Egyptian',
      'Lebanese',
      'ModernEuropean',
      'Mongolian',
      'Moroccan',
      'Nicaraguan',
      'Noodles',
      'Pizza',
      'Polish',
      'Polynesian',
      'Portuguese',
      'Poutineries',
      'Russian',
      'Salad',
      'Sandwiches',
      'Scandinavian',
      'Scottish',
      'Seafood',
      'Singaporean',
      'Soup',
      'Southern',
      'Spanish',
      'Steakhouses',
      'Thai',
      'Turkish',
      'Ukrainian',
      'Uzbek',
      'Vegan',
      'Vegetarian',
      'Vietnamese',
      'Waffles',
      'Wraps'
    ],
    Restaurant: [
      'Acai Bowls',
      'Bagels',
      'Bakeries',
      'Beer, Wine & Spirits',
      'Beverage Store',
      'Breweries',
      'Brewpubs',
      'Bubble Tea',
      'Butcher',
      'CSA',
      'Chimney Cakes',
      'Cideries',
      'Coffee & Tea',
      'Coffee Roasteries',
      'Convenience Stores',
      'Cupcakes',
      'Custom Cakes',
      'Desserts',
      'Distilleries',
      'Do-It-Yourself Food',
      'Donuts',
      'Empanadas',
      'Farmers Market',
      'Food Delivery Services',
      'Food Trucks',
      'Gelato',
      'Grocery',
      'Honey',
      'Ice Cream & Frozen Yogurt',
      'Imported Food',
      'International Grocery',
      'Internet Cafes',
      'Juice Bars & Smoothies',
      'Kombucha',
      'Organic Stores',
      'Patisserie/Cake Shop',
      'Piadina',
      'Poke',
      'Pretzels',
      'Shaved Ice',
      'Shaved Snow',
      'Smokehouse',
      'Candy Stores',
      'Cheese Shops',
      'Chocolatiers & Shops',
      'Fruits & Veggies',
      'Health Markets',
      'Herbs & Spices',
      'Macarons',
      'Meat Shops',
      'Olive Oil',
      'Pasta Shops',
      'Popcorn Shops',
      'Seafood Markets',
      'Street Vendors',
      'Tea Rooms',
      'Water Stores',
      'Wineries'
    ]
};

module.exports = { 
    address,
    city,
    state,
    postalCode,
    tel,
    url,
    categories,
}