CREATE TABLE restaurant (id serial primary key, name char(25), dollars integer, address char(25), city char(25), state char(25), postalCode char(25), latitude char(25), longitude char(25), tel char(25), url char(25), claimed int, yelpingSince char(60));

\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo1.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo2.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo3.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo4.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo5.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo6.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo7.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo8.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo9.csv' DELIMITER ',' CSV HEADER;
\COPY restaurant(name, dollars, address, city, state, postalCode, latitude, longitude, tel, url, claimed, yelpingSince) FROM 'C:\Users\Spencer\Desktop\Hack-Reactor Projects\header-map\database\csvData\restaurantInfo\resInfo10.csv' DELIMITER ',' CSV HEADER;
